### ISSUE TITLE
[Feature] Include werewolf token for Jaul's alternate form and update his statistics to link an effect that changes token accordingly

### ISSUE THREAD

**Issue by TikaelSol** [foundryvtt/foundryvtt-premium-content#102]
### What happened?

Jaul could use a werewolf form token and an effect to swap to that art when he transforms.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.1.0

**Comment by anathemamask** [comment]
Token submitted but update to rule element for effect is in @silvative 's hands

**Comment by silvative** [comment]
Effect is fully implemented and linked to in a journal. His synthetic actor has been updated so that he has the "human" effect active when first met. If this ends up being a source of frustration it can be reverted. 

[output.webm](https://user-images.githubusercontent.com/66365038/208303433-2e1aa69b-fc2c-4b20-87a5-fcf88a415ef6.webm)
