### ISSUE TITLE
[feature]: Create pre-populated merchant actors for Otari locations and link them in journal

### ISSUE THREAD

**Issue by ggagnon76** [foundryvtt/foundryvtt-premium-content#181]
### What happened?

Not a bug... a feature request (sorry, no other option other than 'bug').

I purchased AV for an upcoming campaign I will GM with the understanding that the majority of the prep is already completed.   For me, this is the **_biggest selling point to purchase these Foundry modules_**.  While preparing, I read the journal entries for the locations in the town of Otari.  I also looked from the point of view of the player to see what they see (which is nothing).

Many of the locations are also merchants (shops).  The journal entries outline what the shops contain, for example: basic adventuring gear, light armor, knick-knacks, occult scrolls, etc...  Seeing as the PF2e system has the mechanics for merchant actors, I don't understand why this is not pre-populated by the module?

For example, In about 3 hours (I am a newbie to PF2e and am unfamiliar with equipment) I redid ALL of the journal entries for the Otari locations to do 2 things:
1) Move any text/tag that shouldn't be visible to a player into a secret block, and
2) Add a link to a merchant I made for that location, populated with items suggested in the journal entry

I then made all the journal locations permissions "Observer" for ALL players so they see all the available locations they can visit when they look at the Otari map.  Making all of the locations "Observer"  is my choice as I feel the town itself is not the focus of the module.  The default can be permissions "None" and the GM can modify the permissions per player or per location as they see fit.

In my game, my players will be able to purchase what they want from merchants without having me (the GM) micromanage that part of the gameplay.  

3 hours of prep is insignificant in the long run, but I feel this is a suggestion that wouldn't be overly difficult to implement and would add value to the module.

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.2.0

**Comment by silvative** [comment]
>  Seeing as the PF2e system has the mechanics for merchant actors, I don't understand why this is not pre-populated by the module?

Thank you for your thought-out suggestion. I do think that this is a route that I do not want to pursue, at least at the moment. The reason is quite simple. The book does not provide a definitive list of exactly which items each vendor has available, merely guidance on themes and classes of item that *might* be found there. The GM is intended to parse that, and if I were to do it for you, it would be editorialisation of the adventure text.

If I simply included every single item in the game that falls under the given categories, the merchant actors would contain hundreds of items each. That isn't an exaggeration- for instance, consider if I gave Morlibint all 1rd-level spell scrolls. There are 337 first-level spells in Pathfinder 2E. Now remember that I'd also want to give him first-level wands, and the scrolls for other levels, as well. I hope you can see how quickly it would become absurd. 

Remember, all of that data is loaded for all users who connect to the game, and for no real benefit whatsoever. It would need to offer some kind of advantage over simply telling their players "you can buy a new weapon at this shop" and explaining how to find the compendium browser. Instead, it would be worse, because the UI does not support and was never intended to support merchants with that many items. There is no searching or filtering, so most GMs would need to delete the majority of items to be able to make the thing useable, at which point we may as well go the other direction and have them create the merchants themselves with just the items they want. That isn't a choice I can make, because it's one that will be different for every GM- there's no point in me trying to guess and create homebrew bespoke item lists. In fact, doing so could well be received very poorly by users who signed up to play Paizo's Abomination Vaults, not Cora's Homebrew.

**Comment by bennyty** [comment]
If others stumble across this and are looking for a set of opinionated shops that fit: Steve from Recall Knowledge and DrentalBot made a module that includes shops for Otari.
(lore) I'm sure Gallentine Deliveries could fetch anything not included (/lore)

https://foundryvtt.com/packages/shopping-experience
https://github.com/Drental/shopping-experience
