### ISSUE TITLE
[Bug]: Missing stuff and doors that should be locked

### ISSUE THREAD

**Issue by WaterpoloBlock** [foundryvtt/foundryvtt-premium-content#195]
### What happened?

I only looked at this within the Forgotten Adventures map, can't speak for the other.

Doors that should be locked as per there description:

- E18
- Two Doors South of F7
- F25
- H46
- I05 (To the west)
- I14
- I19
- I54 and I55
- I60 (To the north)
- J5

H41 is missing 4 Drow Hunters

H26, the Secret Treasury should have Greater Braces of Missile Deflection, not Standard

In H06, for the item Key to Area A7, should be : Key to Area H7

In H4, you are missing 3 x beautiful amethysts worth 20 gp

### What package are you reporting this for?

Pathfinder: Abomination Vaults by Paizo

### Version

1.2

### Relevant log output

```shell
None
```

**Comment by WaterpoloBlock** [comment]
And area I58 should be locked as described in the information for I56.

**Comment by silvative** [comment]
Wow, this was very thorough! Great eye, and thank you for grouping them all up like this. 

All the door changes are applied, and some of the rest too.

I believe padli's key is coming from the system, since in the original book, the Farm was A instead of H. I've fixed it by including an actor override, although I may see if I can get the key removed from the system actor instead.

Beautiful amethysts were already in, linked in the room's description:

![image](https://user-images.githubusercontent.com/66365038/208309043-bf6ed0ff-f865-47d3-9dfa-8abe05a35ef3.png)

Thanks again for the great feedback!

**Comment by WaterpoloBlock** [comment]
Fair enough and happy to help.

One more thing:

Within I51, the treasure hoard should have a +2 Striking Mace, not a generic Mace.

And thank you. I'm generally OCD and been double checking my notes and stuff each chapter a week on the map each week.

Have yet to go over chapter 10, plan to do this coming week.
