### ISSUE TITLE
[Forge-specific bug?]: On Forge-hosted games, hazard and loot actor tokens display default image in imported scenes

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt-premium-content#219]
World actors in the sidebar have the correct artwork and prototype token image. Newly created tokens are also fine. Only preplaced tokens are broken.

Both imports made in fresh worlds with no other modules enabled on the same software versions.

Local install:

![image](https://user-images.githubusercontent.com/66365038/212920605-16d413b5-8da3-40b0-b9f1-e0380e33c980.png)

Forge install: 

![image](https://user-images.githubusercontent.com/66365038/212919844-392b14ef-9fca-4184-b2e6-b7d6087a0220.png)

**Comment by rikmarais** [comment]
Hey there 👋 
This is currently happening on The Forge because the `pf2e` specific [code](https://github.com/foundryvtt/pf2e/blob/master/src/module/scene/token-document/document.ts#L143-L150) that replaces default token images with actor images doesn't recognize Bazaar and Asset Library paths.

I'm including a FVTT v10 script here which you can run in your console or as a macro, which will replace default `pf2e` token images with the actor images, similar to `pf2e`'s built-in fallback.
[fixDefaultIcons.txt](https://github.com/foundryvtt/foundryvtt-premium-content/files/10439943/fixDefaultIcons.txt)

**Comment by CarlosFdez** [comment]
So in a different PR I changed the default icon check to use an endsWith() check instead of a direct comparison. However it turns out that you changed the path from `/systems/pf2e/icons/default-icons/blah.svg` to `/systems/pf2e/assets/icons/default-icons/blah.svg` which foils that check. Is it truely not possible to avoid the "assets" sub-folder?

**Comment by rikmarais** [comment]
Apologies for the late reply! The `assets` subfolder is necessary unfortunately, but we're taking steps to remedy the issue on our side and handle the Assets Library hosted default icons so `pf2e` shouldn't need to make a change.

**Comment by rikmarais** [comment]
This issue has been handled Forge-side and can likely be closed.
