### ISSUE TITLE
Suggestion: Player Refrence Cards

### ISSUE THREAD

**Issue by pontusedberg** [foundryvtt/foundryvtt-premium-content#221]
### What happened?

Heya! in the normal Beginer Box there comes a couple of Player Refrence cards. 
it would be great to have those in the game aswell to give to the player, 
Either as a Macro or just a journal to give to the players to check.

Lots of love
![refrencecards](https://user-images.githubusercontent.com/1547673/213120583-04f50409-4ebb-4d70-bed1-842478ab15fc.png)
![refrenecards2](https://user-images.githubusercontent.com/1547673/213120750-6cc4f201-8f0a-479f-a606-52af43fccec0.png)

### What package are you reporting this for?

Pathfinder: Beginner Box by Paizo

### Version

2.1.1

**Comment by silvative** [comment]
Hey, thank you for the suggestion!
I'm closing this issue as we already have one open with the same suggestion, but your specific feedback won't be lost, since it'll be linked to there. 

I think there are issues with doing this as a journal, since journals cannot save checkbox states. However, I do want to keep an eye on this in case there is a way to do it without downsides.
