### ISSUE TITLE
[Bug]: PF2e Bestiary tokens: Otyugh actor image cut off on left-hand side

### ISSUE THREAD

**Issue by carpebiem** [foundryvtt/foundryvtt-premium-content#223]
### What happened?

Just in the actor image, not the token - poor baby

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.0.2

**Comment by silvative** [comment]
The portrait appears in full for me both in the files and on the sheet

![image](https://user-images.githubusercontent.com/66365038/216595027-b486e47c-fb2b-408e-9745-27351b5d15b9.png)

It is cut off in the sidebar, but that is because of how portraits are cropped to display thumbnails, and affects a great number of creatures beyond just this one.

I'll close this one for now, but if you update and are still having issues that don't match the image I just posted, please reopen.

**Comment by carpebiem** [comment]
Okay, think I had an old PDF to Foundry actor open at the same time to compare and got them mixed up - sorry for the false alarm
