### ISSUE TITLE
Journal Handouts displaying with large amounts of vertical padding in PF2 Beginner Box module

### ISSUE THREAD

**Issue by mike-levenick** [foundryvtt/foundryvtt-premium-content#242]
### What happened?

Description: when selecting "show players" on the included art handouts in the journal for the beginner box, a large amount of vertical padding was seen. This only appears when showing just a specific image--not when showing an entire journal entry, such as the entire NPC gallery. 

Link to what I as the GM saw: https://imgur.com/jqtJ7Zs
Link to what my players saw: https://imgur.com/nPiy7yA

Steps to reproduce:

1. Open the beginner box module from a fresh install
2. Go to the journal
3. Select the NPC gallery or a vignette
4. Click into a specific image so it shows with the transparent/grey background
5. Click Show Players
6. Use the default settings (do not change ownership etc) and show players

Expected behavior: the image shows for the players the same as it shows for the GM

Actual behavior: the image shows with a large amount of padding above and below the image, and the user must scroll down to see the image.

Additional information: I tried downloading a different image of tamily from the internet, and uploaded that to my journal as a new, custom journal entry. Upon showing that image to my players using the workflow above, the image showed correctly, and oddly, other journal entries from the module appear to be working correctly now as well (including ones that failed before).

All of the above was recreated in both Safari as well as Chrome on macOS 13.2. I also disabled all modules/addons other than the PF2 ruleset and the Beginner Box module. 

### What package are you reporting this for?

Pathfinder: Beginner Box by Paizo

### Version

2.1.1

**Comment by silvative** [comment]
Hi, thank you for the thorough report!

I'm not able to reproduce this bug on the latest version of the module. It may also be that the behaviour is not present in the dev version, or that it is caused by a local module or hardware limitation of your player's which I do not have in my testing instance. 

![image](https://user-images.githubusercontent.com/66365038/218428185-2d472766-2c65-4e7e-9c80-ae32d8157d78.png)

For now, I've marked this issue as nonrepro, but if you find that the behaviour persists even after our next release (which should come later this week) then we may need to look into it further.

As a note, you should have access to all of the module's files and assets, so you should not need to find replacement artwork online if you do choose to recreate the journals.
