### ISSUE TITLE
[Feature]: Add additional content from Secrets of Magic to the journal entries

### ISSUE THREAD

**Issue by Farkenar** [foundryvtt/foundryvtt-premium-content#290]
### What happened?

As in the title, every card has its own description in the journal. Every card also has information about what alignment and attribute it is aligned with. 

My suggestion is to add information about the school of magic certain card does represent. In the deck of 52 cards, only 16 have this kind of connection(two for every school of magic), but I reckon that it would be more convenient to add those schools as a part of the card's description instead of manually going through "Secrets of Magic" book to find if one of the cards players have picked isn't by any chance representation of one of the eight magic schools.

As for how to implement it, I think that simply adding "This card can also represent school of magic of <school>" at the end of every journal log for those 16 cards would be good enough.

Below I list every school and cards that represent them. Source of this information is "Secrets Of Magic" book of Pathfinder 2e. pages from 20 to 27.

- **Abjuration**: The Brass Dwarf, The Betrayal
- **Conjuration**: The Midwife, The Peacock
- **Divination**: The Theater, The Vision
- **Enchantment**: The Joke, The Rakshasa
- **Evocation**: The Bear, The Cyclone
- **Illusion**: The Carnival, The Demon’s Lantern
- **Necromancy**: The Survivor, The Sickness
- **Transmutation**: The Wanderer, The Twin

### What package are you reporting this for?

Pathfinder: Harrow Deck

### Version

1.0.1

**Comment by silvative** [comment]
I like the idea, although I haven't executed it in the exact way you mentioned. Given the highly niche nature of the information, I didn't want to clutter up the card descriptions by including it there, especially since doing so might imply this is an important piece of mechanical information rather than just an additional lore tidbit. So, instead, I've added a table to the journals:

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/66365038/31299955-b064-4ce5-8fab-41aed5011b90)
