### ISSUE TITLE
[Bug]: Scene Belcorra's retreat, trying to load wrong token

### ISSUE THREAD

**Issue by TheSchnucki** [foundryvtt/foundryvtt-premium-content#301]
### What happened?

I tried to open the scene Belcorra's Retreat (remodelled Map) and it only showed a black screen after loading. Resulted in all other scenes also having just a black screen.

I noticed that the scene Belcorra's Retreat tries to load a token named crawing-hand.webp, but the only available token similar in that folder would be crawling-hand.webp. After I renamed the token in the assets folder, everything was fine.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

latest

### Relevant log output

```shell
I would have to revert the solution to get that, you probably can see it yourself first time.
```

**Comment by silvative** [comment]
I can confirm having encountered the same bug before. While the broken image link is something this module should fix, my hope is that a change to core will prevent it from breaking the scene entirely. I'm told that changing your performance setting in Foundry can sometimes allow you to access the scene in this case due to the issue being a race condition.
