### ISSUE TITLE
[Bug]: Tome of Beasts and Book of Lairs

### ISSUE THREAD

**Issue by YenBenGrey** [foundryvtt/foundryvtt-premium-content#312]
### What happened?

When you choose these two modules in your world they work and are there. When you log out and log back in they are unchecked. You have to re-check them every time you open the world. 

### What package are you reporting this for?

Tome of Beasts by Kobold Press

### Version

1.2.0 for both

**Comment by mattexdee** [comment]
Thanks for raising this. I've found the issue and released an updated version (1.2.1) for both modules that resolves it. In case anyone else is running into this issue it looks like the issue is occurring when the `relationships` field in the `module.json` is defined like this:
```
  "relationships": {
    "systems": [{"id": "dnd5e"}],
    "requires": [{"id": "dnd5e", "type": "system"}]
  },
```
For some reason the core software doesn't like both of those existing. Removing the `requires` stops it from occurring. It should look like this in the end:

```
  "relationships": {
    "systems": [{"id": "dnd5e"}],
  },
```

In general `system` requirements should always be defined in the `systems` field and not in the `required` field.
