### ISSUE TITLE
[Bug]: Foundry v11 - Abomination vaults PF2e module loses all formatting when foundry upgraded to V11

### ISSUE THREAD

**Issue by sesopenko** [foundryvtt/foundryvtt-premium-content#323]
### What happened?

After upgrading foundry to v11, then updating the pathfinder 2e game system, all of the journal entries lose their formatting.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.0.0

**Comment by DrDebuff** [comment]
I just had the same problem. After migrating worlds following an update, all modules are uninstalled. It doesn’t look like it at first, but that includes abomination vaults. Go to manage modules and make sure to reactivate the adventure path module. All journal formatting should be restored.

**Comment by silvative** [comment]
I believe that DrDebuff is most likely correct- if that's not the case, my followup suggestion is to uninstall and reinstall the module, as it's not an error I can reproduce. If the issue persists even with the system and module on their latest versions, then definitely let me know and we can try to help troubleshoot the issue further for you.

**Comment by DrDebuff** [comment]
Thank you for your followup. The issue was user error. The module was simply deactivated. It didn’t occur to me as a possibility since I was still using the maps, monsters, journals, etc. I reactivated the module and everything was fine. Thanks again. Sent from my iPhoneOn Feb 25, 2024, at 2:19 PM, Cora ***@***.***> wrote:﻿
I believe that DrDebuff is most likely correct- if that's not the case, my followup suggestion is to uninstall and reinstall the module, as it's not an error I can reproduce. If the issue persists even with the system and module on their latest versions, then definitely let me know and we can try to help troubleshoot the issue further for you.
