### ISSUE TITLE
[Feature]: v1.2.3 manifest mismatches

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/foundryvtt-premium-content#326]
### What is the feature?

**Request**:
If possible, please release a v1.2.4 version bump of `pf2e-ap178-punks-in-a-powderkeg` so that the Forge Bazaar can receive the correct new v10 manifest info for the dependency.

- Foundry listing contains v1.2.2 but not v1.2.3, though the manifest points to v1.2.3 

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/34374883/43afecd9-0b92-403d-b0ff-07a036d2f11e)
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/34374883/71ea0d97-7839-448b-abc9-9d42102e6447)

- The v1.2.3 manifest at https://cdn.paizo.com/foundry/modules/pf2e-ap178-punks-in-a-powderkeg/module-v10.json was likely updated so that the relationship for the basis pack points to a v10 manifest, but no new version of the `pf2e-ap178-punks-in-a-powderkeg` main module was released at the time of that update. This means that certain integrations like the Forge bazaar did not receive the updated manifest.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/34374883/543a11f6-0cf9-4a2e-bad8-b4110de9aea3)

**Note**: This is not a request for **Abomination Vaults**, but for [**Outlaws of Alkenstar**](https://foundryvtt.com/packages/package/pf2e-ap178-punks-in-a-powderkeg) (which can't currently be selected via the new issue UI).

### What package are you reporting this for?

Pathfinder: Abomination Vaults

**Comment by mattexdee** [comment]
Hey @rikmarais, thanks for reaching out with this issue! As part of our Paizo partnership we have only developed the Beginner Box, Abomination Vaults, and the upcoming Kingmaker module. The others, including Punks in a Powderkeg, were developed by the folks over at Sigil. I've passed your issue along to them and they asked that I point you to their [support page](https://support.sigil-services.com/) so they can help get this resolved.

Since this issue isn't related to one of our pieces of premium content I'll close this issue but please feel free to reach out to us if you run into any other issues!

**Comment by rikmarais** [comment]
Thanks so much! @mattexdee !
