### ISSUE TITLE
[Bug]: Broken content links

### ISSUE THREAD

**Issue by LukasPrism** [foundryvtt/foundryvtt-premium-content#329]
### What happened?

Not a huge deal but the Building Encounters journal which has an icon in the hotbar on install doesn't seem to have any working content links. I'm not even sure how to find the Encounter Budget document it's referencing:
<img width="559" alt="Screenshot 2023-08-31 at 8 39 48 AM" src="https://github.com/foundryvtt/foundryvtt-premium-content/assets/104886594/fcdab5f4-e040-4d90-82b8-773adf887bdf">

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

3.0.0

**Comment by pearcebasmanm** [comment]
To add, this also occurs with the Module turned off, so it isn't a custom formatting problem.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/75871317/2010fff5-d5e5-4bc2-b65f-de4c31c5d883)

In fact, I could recreate it with a new journal and page (as the Building Encounters macro just pulls up a page from the "Beginner's Guide: Gamemastering" journal).

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/75871317/3d2cbada-491f-447f-bb4d-53297e89ad8f)

It seems like a page sheet can only ever be in edit mode, which makes sense as you usually press the edit button in a journal to get to it. However it is a usability problem that the macro for helping new players brings up a page with UUIDs instead of working links. I don't know if there's a way to do it, but ideally the macro would instead open the Gamemastering journal on the Building Encounters page like so:

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/75871317/3b520d72-eb03-4fb5-83ab-f5970c956216)

**Comment by silvative** [comment]
I've updated the macros to slightly more advanced versions which open the journal at those pages, instead of opening the page view in "popped out" mode. This should resolve the issue for you on a reimport (in our next release) !
