### ISSUE TITLE
[Bug]: Creatures already on scenes dont have conditions applied Pathfinder beginner box 

### ISSUE THREAD

**Issue by Atticus-Withakay** [foundryvtt/foundryvtt-premium-content#331]
### What happened?

While looking at starting the pathfinder 2e beginner box i noticed that the zombie shamblers on floor 1 have the condition "slow" however this condition is not set on the token just mentioned in the sheet. This is also the case of the imported zombie shambler however if you grab a fresh token from the pf2e compendium it has the slow condition applied. 

Im sure this will apply to other tokens that are already in scenes that they dont have the latest condition settings from creatures in the compendium. 

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

3.0.0

**Comment by silvative** [comment]
I'm not sure, but this may be a system issue- at a quick glance the BB zombie shambler doesn't seem to have the condition in the compendium? I'll have to check whether it's supposed to have it in the book or if it's intentionally "simplified" somehow

**Comment by Atticus-Withakay** [comment]
Correct the BB zombie shambler doesn't have the condition set on the token while the pf2e system zombie shambler does. If creatures have conditions they should be set on the tokens so foundry works as expected. The BB needs to be aligned with the pf2e compendium.

**Comment by silvative** [comment]
Thank you for the extra information!

I had a look further- it seems like the reason for this is that the Beginner Box zombie doesn't have the "slowed" condition, since the Beginner Box uses a simplified set of rules. However, it has a custom passive which is mechanically identical, so I've added the Slowed condition to it just to make it benefit from any automation. Basically, this wasn't an issue with the Beginner Box, it was a just that the data entry in the PF2E system had stuck to the rules as written.

If my changes are approved, then the zombies will both have the slowed condition, which will solve your problem- but if the PF2E dev team decide to keep things the way they are, you can always opt to use the Bestiary creatures instead by deselecting "use beginner box creatures" in the import settings for the Beginner Box module- if you're ready to start playing with the full rules there really isn't much reason not to.
