### ISSUE TITLE
Installation Issues on Forge

### ISSUE THREAD

**Issue by Gameboygramps** [foundryvtt/foundryvtt-premium-content#343]
### What happened?

Receiving the following when trying to install this new AP Module for Kingmaker:
"Failed to install module: /forge-vtt/users/64adc0feecec46c0dd91fec8/Data/modules/pf2e-kingmaker/module.json: Unexpected end of JSON input"

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by briwalpole** [comment]
I'm receiving this error as well. I was able to install the module before the 1.01 update but can't any more.

**Comment by silvative** [comment]
Are you both using Forge? This may be an issue specific to something about their infrastructure, but we should investigate further. It may be worth contacting their support to see if they recognise the error?

**Comment by briwalpole** [comment]
Correct. I'll reach out to them as well! Currently re-downloading Foundry and seeing if I can't get the module running locally.

**Comment by Gameboygramps** [comment]
Hi Cora,

Yes, this is through Forge. I saw you mention to use 1.0.0 on the unboxing
video that went up on Youtube yesterday so tried that, using the manifest
url from the foundry Kingmaker site, rather than what Forge had listed in
their setup and it downloaded correctly!

Thanks,
- Jared

**Comment by briwalpole** [comment]
I'm still on the outs. Tried using the 1.0.0 manifest URL and that didn't work for me. I am in contact with Forge assistance and have heard that this is a problem running across a few premium modules at the moment.

**Comment by vdrake77** [comment]
I think it might be related to the size of the download.

The storyteller limits you to one gig of data, and I believe the pathfinder zip might be larger that.

**Comment by Gameboygramps** [comment]
This is something I noticed while attempting.

If you download but don't try to launch right away, you can keep an eye on
your game data - it skyrockets during download but then eased back for me
after it had finished so I was able to open the game no problem and add the
module.

**Comment by briwalpole** [comment]
Download rate isn't the issue for me. I click "install" and it gives me "Failed to install module: /forge-vtt/users/624ca7cbd41b54571099dcf7/Data/modules/pf2e-kingmaker/module.json: Unexpected end of JSON input". I'm unable to download the mod at all but was able to download it on Wednesday afternoon.

**Comment by rikmarais** [comment]
Hey there 👋

This error is caused by leftover files due to a failed install on Forge. Failed installs should no longer be happening, but if you are currently encountering `Unexpected end of JSON input` when trying to install, please go to https://forge-vtt.com/setup and click on `View Data Storage` in the `Others` tab, the temporary files would appear under the `Directories` section (next to where the `dndbeyond` folder appears here) and can be deleted from there, after which a re-install would proceed without error.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/34374883/86c7a8d2-d2a9-4c22-8eb6-8451dc80d5cc)
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/34374883/30d139a0-94ec-435c-859f-8b55ad8f71eb)

Please let me know here or in our [Discord](https://forge-vtt.com/discord)'s `#forge-support` channel if you encounter any errors!
