### ISSUE TITLE
[Feature]: Consider a means to deliver changelogs within Foundry (eg journal entry, button on import window?)

### ISSUE THREAD

**Issue by jbblanchet** [foundryvtt/foundryvtt-premium-content#349]
### What is the feature?

It would be nice to be able to access a changelog for newer versions of modules. A lot of the open sourced ones will have the changelog available on the repo, but for these premium modules I couldn't find one.

Thanks for considering the idea.

### What package are you reporting this for?

None

**Comment by silvative** [comment]
Hey! I've added the issues closed in 1.0.1 to a milestone which you can find here:
<https://github.com/foundryvtt/foundryvtt-premium-content/milestone/16>
That is generally how I have approached patchnotes for our premium content, though I also usually post an announcement on our discord. Sorry for the delay in this instance! We were trying to get this one out as quickly as possible on the heels of the release.

We'll try to keep that pattern up in the future, but I'm also open to improving our processes, so I've renamed this issue accordingly since I think it's a worthy thing to explore.

**Comment by jbblanchet** [comment]
Thanks for the feedback. I'll freely admit that I'm not much of a discord user. I'll use the milestones to look up changes for now. Keep up the good work!
