### ISSUE TITLE
[Bug]: Kingmaker Hex Map Issues

### ISSUE THREAD

**Issue by StrangeMortis** [foundryvtt/foundryvtt-premium-content#357]
### What happened?

In version 1.0I had been having an issue where once a hex had been marked in any way (cleared, claimed etc.) it could not be unmarked and so was permanantly in this state. Also when an area was marked explored it did not remove the blach and white 'drawn' overlay to replace it with the colour map beneath.

I cannot confirm whether this is the case in 1.0.1 as in this version I have no option to select the hexes as I did in 1.0.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Sorry, I might need a little more information to understand the exact problem here. It seems like there are several issues in this post, so I'll try to answer them one by one.

> In version 1.0I had been having an issue where once a hex had been marked in any way (cleared, claimed etc.) it could not be unmarked and so was permanantly in this state. I cannot confirm whether this is the case in 1.0.1 

This issue was fixed in 1.0.1, so you need to be on 1.0.1 to get the fix. If you're using 1.0.0, then you should update. If you're using 1.0.1 and are still having the issue, then we need to investigate further.

> Also when an area was marked explored it did not remove the blach and white 'drawn' overlay to replace it with the colour map beneath.

This is working as expected, the "explored" boolean is for tracking hexploration status and POI visibility, not for clearing fog

>  I have no option to select the hexes as I did in 1.0.

This sounds unintended, can you explain the problem in more detail?

**Comment by silvative** [comment]
Closed under the assumption this was fixed by updating to 1.0.1 - reopen if any of this is still a problem!
