### ISSUE TITLE
[Bug]: Vordakai is missing a 3rd 6th level spellslot: dominate

### ISSUE THREAD

**Issue by Weasel8675** [foundryvtt/foundryvtt-premium-content#359]
### What happened?

As per the kingmaker AP, Vordakai has 3 6th level spellslots, but is missing his 3rd in the module. He should have dominate.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
I can confirm there are only two level 6 spell slots, but it seems like the issue is at a system level, since it's also the case in the compendiums (and we aren't modifying Vordakai's statistics).

Since a fix has to be implemented on the system side, I've marked it not planned for the module, even though it does seem like something that should be resolved. 

I may be making a system MR for other Kingmaker related issues at some point, at which time I'll make sure to check if this one needs doing too, but I'm not sure when there will be time for that, so if you want to see this fixed sooner I recommend posting an issue on the PF2E system's repo (here: <https://github.com/foundryvtt/pf2e>).
