### ISSUE TITLE
[Feature]: Stag Lord's "Hunt Prey" action should list the actual rules

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/foundryvtt-premium-content#376]
### What is the feature?

I appreciate the Adventure says:
> As ranger (Pathfinder Core Rulebook 168).
But it would be good to include the text of this ability in the actual actor's sheet!

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
Replying once but also applies to https://github.com/foundryvtt/foundryvtt-premium-content/issues/375 and https://github.com/foundryvtt/foundryvtt-premium-content/issues/377

The stat blocks for NPCs used by this module are imported from the PF2E system, so issues relating to them and how they are formatted are best addressed at the system source rather than by a downstream modification from us. Because of that, I'm closing the issues here, but I have taken note of them so that I can take a look at this if I find myself making system changes for another reason. In the meantime if you'd like to create an issue on the PF2E system's issue tracker they may fix it before I get there- you can find their issue tracker here: https://github.com/foundryvtt/pf2e/issues . I would suggest combining all three into one post to make it easier for them to be tracked and organised!
