### ISSUE TITLE
[Bug]: Reopening Crooked Falls and Fort Sorenko having their locations swapped

### ISSUE THREAD

**Issue by joshuakaras** [foundryvtt/foundryvtt-premium-content#399]
### What happened?

Thanks for the reply on this previously. Here is the map from book 3 of Kingmaker for the 1st edition. 

![276068131-a9365c5d-ffbc-4114-8521-2112376291b1](https://github.com/foundryvtt/foundryvtt-premium-content/assets/39630313/2fde149f-c214-4fba-af6e-6c34f503cef2)

Discussions from the errata are here - https://paizo.com/threads/rzs43olf?Kingmaker-Adventure-Path-2E-Errata#1 - James Jacobs has only replied to correct proposed erratas that weren't correct, which implies that RL4 and RL5 are indeed swapped.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
Hi! It's interesting to see that the locations were swapped between the editions, but as we are adapting Kingmaker 2E, I don't think we should consider the 1E version's map to be "more" canon than the 2E one. If Paizo let us know this was a mistake we can make a change, but otherwise, we will treat the 2E map as the higher authority.
