### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#432]
### What happened?

looks like you've switched a C7 & a C8 around along the bottom from the left, staying with rooms along the outer edge of the building, it should be C7, C7, C7, C7, C**8**, but you've got a C7 room (judging by the content of the room) instead of that last C8
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/88220878/10b3efc3-0890-4ac9-83a2-6ea42e439134)
indicated in the ss above
the coresponding area from the pdf
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/88220878/8b231d25-2709-43a7-997b-b0ab3f6b5028)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

1.0.1

**Comment by silvative** [comment]
This is indeed a change from the book, although not (as far as I know) an unintentional one- while Narchy and Alaustin stayed as close to the original maps as possible, it's not unusual for them to tweak minor details like the sizes of rooms or their placement when a change is appropriate. Most often (such as in the case for the Varnhold blockhouse) when we deviate from the book's map it's done in order to better adhere to the written descriptions of the areas,, but in others (like this one) it was more a subjective choice, so I can see why it may look like a mistake. That said, if I recall correctly, there are several storage rooms and several ballista rooms, and so while this is a difference from the book it isn't one that has a large impact the way that the palace map plays out.

For that reason, for now I'm going to close the issue as not planned, but if I have forgotten or overlooked any negative consequences to the change please let me know. It's not out of the question that we may have revisions made, but I would want to be sure it was merited.
