### ISSUE TITLE
[Bug]: Macro in Deadtide for Otari prelude Journal doesn't work

### ISSUE THREAD

**Issue by asawolow** [foundryvtt/foundryvtt-premium-content#434]
### What happened?

A bug happened! While checking Chapter 2: Deadtide Prelude journal this macro @Macro[0C1vnwN5UaW0aWFQ]{Deadtide for Otari} doesn't seem to show what the descriptions says. which is spectral glow to descend onto the graveyard.

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.0

**Comment by silvative** [comment]
Hi, I just tested the macro and it seemed to work for me- do note that the macro is intended to be used on the Landing screen or the Otari scene, is it possible that you're on the Otari Graveyard scene already? It doesn't do anything there, since by the time the players reach that scene the event is already well underway.
