### ISSUE TITLE
[Bug]: Scene links don't open their corresponding config window

### ISSUE THREAD

**Issue by tagnullde** [foundryvtt/foundryvtt-premium-content#435]
### What happened?

As the title suggests.
The Scene link in the "The Tiger Lord Camp" of the Questline "Blood for Blood" has the wrong ID and won't open.

![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/44159008/a35d36a5-b163-4c12-94cd-197a8b8ab814)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
Hmm, that's definitely the correct ID. I wonder why the link isn't opening the scene config as expected? I seem to get the same issue on all of the scene links.

**Comment by tagnullde** [comment]
In the Journal is a different ID than in the tooltip though.
Either way - if the ID is correct after all, this or #496 might then be duplicates. I filed the other issue as a separate case.

**Comment by silvative** [comment]
> In the Journal is a different ID than in the tooltip though. Either way - if the ID is correct after all, this and [#496](https://github.com/foundryvtt/foundryvtt-premium-content/issues/496) might then be duplicates or even related. I filed the other issue as a separate case.

Ah, you're right! I didn't look closely enough at your image, but I think I must have already fixed that link in our dev world. It turns out the reason I still couldn't open it may have been related to issue #496, so this one specifically should be safe to close, though I'm not sure if the problem itself will be resolved or not yet
