### ISSUE TITLE
Kingmaker re-import hangs at 72%, an hour or longer.

### ISSUE THREAD

**Issue by AtreidesGhola** [foundryvtt/foundryvtt-premium-content#444]
### What happened?

Importing hangs at 72% for over an hour.

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0

**Comment by silvative** [comment]
I can't reproduce this issue locally- it may be worth deleting and reinstalling the module, as well as attempting the import again with all other modules disabled. 

It shouldn't ever take more than a minute or two at most to import the adventure- if it isn't done in ten, I'd suggest taking the above steps since I can't imagine it's going to finish.
