### ISSUE TITLE
[Feature]: link to bubonic plague, or maybe an edited version you create?

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#450]
### What is the feature?

in Ch 10 pt 2, the pathway perils can expose the PCs to a special version of bubonic plague, but with virulent trait added and a higher DC - it'd be useful to have a link to a version of this disease that you've imported and edited to have the correct info, atm, assuming no modules, a GM would have look it up in the compendium and keep in their head the changes, which isn't ideal

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by dharkus5000** [comment]
actually, the disease isn't even in the system, except on the master vrylokas vampires! it does look to be the same effects, so that could be used as a base!
[fvtt-Item-thousandbreaths-bubonic-plague-eeuAVRNV5xI35I33.json](https://github.com/foundryvtt/foundryvtt-premium-content/files/13799437/fvtt-Item-thousandbreaths-bubonic-plague-eeuAVRNV5xI35I33.json)
something like this

**Comment by silvative** [comment]
Hi, my understanding is that the PF2E system's affliction item is not ready for use yet, so the diseases and poisons do not yet exist. Once they do, it would make sense to link to those items in the journals, but it would be unnecessary to create them in Kingmaker proper since they will presumably exist in the system compendiums at that point.
