### ISSUE TITLE
[Bug]: missing loot actor - ch 11 B3

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/foundryvtt-premium-content#461]
### What happened?

>  These feelings automatically draw each PC to an item of food or drink in the kitchen they instinctively recognize as a cherished meal from childhood. Whatever the form of this meal, the PC also understands immediately upon touching the meal that it functions as an elixir of rejuvenation.
there's no loot actor to contain these elixirs

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.0.0

**Comment by silvative** [comment]
Unfortunately, I can't create the items beforehand as I don't know what each character's favourite childhood meal would be. I do link to the item in the journals so that GMs can drag it out and customise it, however. I support I could create a custom "cherished childhood meal" item instead, but the advantage of linking to the pristine system item instead is that it is far more resilient to future updates than a custom one is.
