### ISSUE TITLE
[Feature]: Kingmaker: a tile with all of the numbers and letters of the quests on the stolen lands map

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/foundryvtt-premium-content#533]
### What is the feature?

id like a tile that has the names of the areas on the map but also the quests with their respective letters and names so i can have that as a reference as a gm. but not nessicarily let the players see this either.

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
This is a good suggestion, but I don't think it's something we'll be doing, as it would require a bit too much subjective ruling on my part, since many quests span several areas. Thankfully, there is a journal entry that gives a summary of all of the quests in the adventure (and links to them), which can be used as a quick reference if needed. You can find it under the Appendices folder on the Journals tab, in _Appendix 2d: Quests_ on the page _Index_.
