### ISSUE TITLE
[Bug]: incorrect encounter at a23 in map aldori seige west 

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/foundryvtt-premium-content#535]
### What happened?

the encounter should have two black tear cutthroats not 4. which takes it from severe to extreme for a party of 4. 

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.1.0

### Relevant log output

```shell
n/a
```

**Comment by silvative** [comment]
From my memory, there's an inconsistency in the text for this encounter- the number of enemies is listed in two places and it doesn't match. We decided on the lower number because- as you point out- the severity of the encounter matches the lower one. I also figured that a Severe encounter at level 1 is already incredibly harsh, so I wouldn't want to subject anyone's party to a level 1 Extreme !
