### ISSUE TITLE
Token art swapped.

### ISSUE THREAD

**Issue by anchovy369** [foundryvtt/foundryvtt-premium-content#553]
### What happened?

Token and portrait art for the Nosferatu Malefactor and the Nosferatu Overlord are swapped.

### What package are you reporting this for?

Pathfinder Token Pack: Bestiaries

### Version

1.1.1

**Comment by silvative** [comment]
It's a distant memory at this point, but from what I recall, we had these swapped relative to Archives of Nethys, but that it was intentional based on the original filenames and their appearance- I was fairly sure that they had been mislabelled in a book or on Nethys, and that we actually had them the right way around. I can take a look later on for you to make sure I'm not wrong about that!

**Comment by anchovy369** [comment]
OK. Thanks!
