### ISSUE TITLE
[Bug]: when creating journal links on the macro bar they look broken.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt-premium-content#562]
### What happened?

when you drag any of the journals inside the premade journals to the macro bar they look like this 
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/62528192/43b3ef38-1cd2-42e9-9aa3-d0f67500a17d)
and i was wondering if this is a bug or a feature request to be able to get looked at?

the reason why id ask is that id like to be able to reference parts of the journals with all of the formatting to send to chat. especially the influence sections. 

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.1.0

### Relevant log output

```shell
none
```

**Comment by silvative** [comment]
Core Foundry behaviour is that dragging a journal page to the macro bar creates a macro that opens that journal _page_, which is different from opening the journal entry. When a page is opened by itself, it opens in its "popped out" form, which you may also recognise as the way that a page is opened when you are editing it. 

We do extend as many of our CSS styles to the journal page's "popped out" mode as possible, but I agree that it looks like a substantial visual downgrade, and it's not the best reading experience. Unfortunately, if I wanted to remedy that and make the journal page look the same as the journal entry proper, it would require locking down that page view, preventing it from being edited at all, which would mean that users would lose the ability to make changes to the journal content. This is a pretty popular thing to do (even though it isn't recommended) and I wouldn't feel great about doing it. 

It may be that core Foundry will modify the behaviour of the default journal macro at some point, which would make this easier, but if not, I would recommend replacing it with one that has the behaviour you're looking for. You can see an example of this by looking at the macro in Kingmaker that opens the changelog. Instead of opening the page, it opens the journal and activates the desired page, which is much more consistent with the behaviour that most people are expecting. If you want to use that macro to open other journals, you can just change the IDs in the macro. 

I'm sorry that I can't directly resolve the issue, but I hope this helps to explain the behaviour that you are experiencing, and I hope that one of these workarounds will be useful to you!
