### ISSUE TITLE
[Bug]: The Forgotten Keep (NM5). Main gate "Falling portcullis" action does not automatically roll damage.

### ISSUE THREAD

**Issue by BloodyChef** [foundryvtt/foundryvtt-premium-content#575]
### What happened?

Main gate "Falling portcullis" action does not automatically roll damage. The button of damage gives only the passive damage.
![image](https://github.com/foundryvtt/foundryvtt-premium-content/assets/149866613/98ef25ff-721e-4683-87ec-c072060436ae)

### What package are you reporting this for?

Pathfinder: Kingmaker

### Version

2.1.0

**Comment by silvative** [comment]
Hi! Thank you for reporting this- there does seem to be an oversight in the inline roll's formatting. 
Unfortunately, because the actor stat blocks we use for NPCs and hazards are pulled from the Pathfinder system's built-in compendiums during the import process, we don't have the ability to resolve these sorts of problems "in-module". However, the upside is that the system data entry is continually improving and expanding, and their fixes do seamlessly propagate downwards to users of adventure modules.

As a result of that dynamic, I'll close this issue, but I've created a new one on the PF2E system's repository to track the problem there.
