### ISSUE TITLE
[Bug]: Doppelganger Disguise Switcher macro not working.

### ISSUE THREAD

**Issue by tslewis123** [foundryvtt/foundryvtt-premium-content#579]
### What happened?

It's supposed to change the token for the doppelganger in area W18 of Wave Echo Cave to either a drow or Nundro Stoneseeker, but it doesn't do anything.

### What package are you reporting this for?

Phandelver and Below: The Shattered Obelisk

### Version

1.1.0

**Comment by mattexdee** [comment]
I was not able to reproduce the issue in 1.1.0 and the latest 3.2.0 D&D 5E game system. @tslewis123, could you share some more info about what happens when you experience this issue and if it still occurs with all other modules disabled? I should note that the token you want to update must be selected when you run the macro. I've added a notification about this in the macro in the meantime.

**Comment by tslewis123** [comment]
Whenever I select Vhalak and run the macro, it brings up the text box, but
doesn't change the token. I did some experimenting and discovered that it
works in older versions of foundry, but not version 12.

**Comment by mattexdee** [comment]
Ah, thank you for that added detail. I'll get that fixed!

**Comment by mattexdee** [comment]
Fixed as part of our [1.2.0 release](<https://github.com/foundryvtt/foundryvtt-premium-content/discussions/594>).
