### ISSUE TITLE
[Feature]:  please add text indications for the rivers on the kingmaker stolen lands map and the sepia versions

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt-premium-content#581]
### What is the feature?

currently there is no indication on the maps to show which river is which, alot of the quests and rumours hint at them being near the different types of rivers. 

without there being text or something written via the art for the map its hard to know where this is. and even trying to know this via the pdf is difficult. so i would like to have this as a standardised affair on both the sepia overlay and the main map. 

### What package are you reporting this for?

Pathfinder: Kingmaker

**Comment by silvative** [comment]
Hi! I can definitely understand why you would want this, feature, but sadly it's not something we can easily do. One of the reasons is that there is no single canonical source that we can use to find the names of each of the rivers. While some rivers are named in the adventure text, many are not, and this isn't something I'm comfortable with us making up to fill in the blanks. While we could reach for other Paizo publications and official maps for additional information, in some cases this only makes the matter more difficult to adjudicate, as the rivers aren't always in the same location between various maps, including sometimes being on different sides of mountain ranges, cities, and other landmarks. Without a way to authoritatively determine the "official" names of each river without being wrong from someone's point of view, it's essentially impossible for us to integrate something like this into the module. 

I think it's best for GMs to feel empowered to make judgement calls on these sorts of things, as their word can then be the law for their respective playthroughs, whereas any efforts on our part will inevitably contradict the preferences and canon of a certain percentage of the playterbase. It's also possible for community members to create and share overlays between themselves, since they aren't held to the strictest standard of "canon" and can simply make the best judgements for themselves.
