### ISSUE TITLE
[Bug]: Playlists start playing after importing when they shouldn't

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt-premium-content#592]
### What happened?

Hey Cora,

I just noticed that AV has the Musical Stings playlist running when you import the playlists. Don't even need to import the whole adventure, just the playlists is enough. Also it's set to sequential playback, which seems a bit odd to me.

You might need to reload after the import for the music to start, but you can see that it is supposedly running immediately.

Happens on a clean import

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

**Comment by silvative** [comment]
How odd! I think I've seen a bug like this in the past due to sounds running while the adventure was packaged, though it may also be related to scenes autoplaying their associated playlists. I've at least confirmed it's not happening on the version I'm working on right now, so the next release should fix it!
