### ISSUE TITLE
[Bug]: Several Family tags missing from the filters

### ISSUE THREAD

**Issue by DuskyVoltage** [foundryvtt/foundryvtt-premium-content#648]
### What happened?

The "Family" section of the filters is missing several tags that are present in the database.

Image of family tags currently available:
![image](https://github.com/user-attachments/assets/af1079e9-38eb-4f70-aed0-b1448f855911)

The missing tags seem to be tags from the NPC Gallery, such a Criminals, Foresters, Courtier, Magistrate, etc

### What package are you reporting this for?

Pathfinder Tokens: Characters

### Version

1.0.1

**Comment by silvative** [comment]
This was intentional- I left out some of the tags that were too "edge case" to be easily applied across the board. I deliberated on this so I could be convinced to go back (I technically have done the data entry already using the old tags), but I would need to be confident that it would be an overall quality increase, and not just me diluting the tag groups with a bunch of extra niche ones (I found that, for example, I was using Courtier a lot, but Magistrate was incredibly specific and nearly never used).  

Basically, the tags Paizo used in the GMG aren't used in other publications (at least for the moment), so it was very subjective to decide whether a given piece of art "felt" like a "villain" or "devotee". That's why I condensed and replaced them with more broad categories of my own- "outcast" for "criminal" and "villain", "sage" for "scholar" and "healer" and "mystic" and "devotee", etc

Officers and seafarers were two that felt like they still justified their existence after I did away with the "old" tags, partly because the Absalom book has so much art for various members of the town guard, so I kept those but otherwise replaced them, and didn't use the other family tags. Because of this, exposing those filters would not be useful as the only pieces that are tagged with them are the GMG pieces (so about four for each one). That might change if Paizo resurrect those tags in future publications, though.
