### ISSUE TITLE
[Bug]: Incorrect sources on Character Gallery

### ISSUE THREAD

**Issue by Zullock** [foundryvtt/foundryvtt-premium-content#663]
### What happened?

Some of the images seem to have incorrect sources listed (probably the variants that didn't have art made for them in either the bestiary book, battlecards or pawn collection), for example the empress ice worm has as a source "Bestiary 3 Pawn Collection", but the art is from Quest for the Frozen Flame.

### What package are you reporting this for?

Pathfinder Tokens: Characters

### Version

1.0.3

**Comment by silvative** [comment]
Thank you for reporting this- please let me know if you find any others as well! The source data for the Bestiaries creatures was something we had to try to reconstruct retroactively and we were certain that many would have slipped through the cracks, but they are things we can rectify if people notice them, so that is very helpful. Hopefully, the Character Gallery datasheet, as well as future modules, should have more accurate sources.
