### ISSUE TITLE
[Bug]: Funny Colours on Abomination Vaults Official module 

### ISSUE THREAD

**Issue by Geluxu** [foundryvtt/foundryvtt-premium-content#673]
### What happened?

All of a sudden, certain scenes have a sort of magenta filter that make the view of the scene a bit uncomfortable. The colours were ok before but now after re-importation everything looks like the second image. 

![SPOILER_image](https://github.com/user-attachments/assets/de3795e4-27e9-4099-b9dd-94ed748b3077)
![SPOILER_image2](https://github.com/user-attachments/assets/6b2e62e9-9c65-491b-aee1-4ff093aff4c1)

### What package are you reporting this for?

Pathfinder: Abomination Vaults

### Version

3.1.3

**Comment by shemetz** [comment]
This bug is happening because Foundry V12 added a new feature, [scene config -> Ambience -> Environmental Lighting](https://github.com/foundryvtt/foundryvtt/issues/9683), and now every AV scene has these custom dark ambience lighting settings:

![image](https://github.com/user-attachments/assets/c191a2c1-0886-47f5-8924-1e1d74ab09b0)

Rather than the default settings:

![image](https://github.com/user-attachments/assets/3e06d5b2-77b9-4e87-9f1e-db5f541f6965)


I'm pretty sure this was unintentionally caused by mistake during the V12 upgrade of the AV module.  

@silvative -- when you fix this, try to figure out why this happened to all scenes here, and whether it happened to other adventure modules too.  Maybe there was some bad migration code?

---

@Geluxu this issue will apply to any scenes imported in these V12 module versions, so it'll remain in your already-imported scenes even after a bugfix update happens.  To fix the tint issue as a user (GM), you'll need to configure the settings of all of your scenes and reset those settings.  To save you some time, I made a macro (or a script for your console) -- run this code and all of the afflicted AV scenes will get their dark ambient lightning reset to 0 hue intensity and -0.25 luminosity:

```js
updates = game.scenes
    .filter(sc => sc.thumb?.includes("modules/pf2e-abomination-vaults/"))
    .filter(sc => sc.environment.dark.intensity == 0.35)
    .map(sc => ({
        _id: sc.id,
        "environment.dark.intensity": 0,
        "environment.dark.luminosity": -0.25
    }))
Scene.updateDocuments(updates)
```

**Comment by silvative** [comment]
Thank you for the thorough breakdown of the issue- it makes it much easier to resolve! You're definitely right that I should check the other adventures for the same problem- I'll have to make a note of it. It's possible that AV suffered because we did a V12 update during the pre-release phases, before these features were finalised, so it may have been caught out by a late change!
