### ISSUE TITLE
[Bug]: Healing enricher for Healer feat incorrect

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/foundryvtt-premium-content#713]
### What happened?

The healing enricher for the healer feat allows a healer to roll another creature's hit die and then add their own proficiency bonus to the roll. 
With how it is currently set up there are two issue:

1. Proficiency is not added to the roll because the formula only uses @attributes.hd.largestAvailable or @attributes.hd.smallestAvailable adding  + @prof could resolve this else using a situational bonus
2. The roll formula looks at the data from the person that put the feature in chat not the person rolling using the enricher. In the example below a barbarian with a hit die of d12 is prompted to roll a d8 because thats the hit die of the bard who has the feat in this example
![image](https://github.com/user-attachments/assets/e2c06149-2082-46fc-a77d-15fe9bd5ecb7)

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by maxobremer** [comment]
in this example the barbarian was under the ownership of player 1, the barbarian token was selected by player 1 and in the user configuration the barbarian was set to player 1's player character

**Comment by mattexdee** [comment]
Ah, this one is tricky since it uses the injured character's hit die but the healer's proficiency. Unfortunately, I was under the impression doing a healing roll like that would draw on the hit die of the person who clicked on it (which is why I didn't include `@prof`) but it looks like that data is backed into the inline roll when it's sent to chat. Unfortunately, I think this might not be something that can implemented cleanly in the current system version. I've noted it with the developers though and we'll see if there's anything we can do that would work well here!
