### ISSUE TITLE
[Bug]: The Dispel Evil and Good spell is missing an activity for 'Break Enchantment'

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt-premium-content#720]
### What happened?

It only has an activity for the Dismissal (saving throw).

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.0.0

**Comment by mattexdee** [comment]
Made some additional changes here:
1. Added a `Cast` activity that consumes the slot and includes the Active Effect.
2. Changed the targeting on the `Dismissal` activity's target to be touch, creature, etc. and removed its spell consumption/duration (since it's used to end the spell early, not cast it).
3. Added a `Break Enchantment` activity with the right targeting that also does not consume a slot and has no duration for the same reason.

Unfortunately, I can't set those activities to end concentration but this should be more accurate now!
