### ISSUE TITLE
[Bug]: College of Dance not 'Dazzling Footworks' Unarmed Strike

### ISSUE THREAD

**Issue by malea-gh** [foundryvtt/foundryvtt-premium-content#759]
### What happened?

The 'Bardic Damage' part of 'Dazzling Footwork' can turn Unarmed Strikes into Dex based attacks, and gives them additional damage based on your Bardic Inspiration die. This should be granted as a feature like it is for monk, but is currently missing.

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.1.2

**Comment by mattexdee** [comment]
The Dazzling Footwork feature includes an Unarmed Strike activity that is configured with the correct dexterity/damage. I can see the desire to have an Unarmed Strike item though since it would appear in the Inventory rather than the Features tab so I'll add one and players can use whichever option suits them.

**Comment by mattexdee** [comment]
Closing as its resolved in the latest update.
