### ISSUE TITLE
[Bug]: Spell Synaptic Static should to offer to apply penalty to tokens that fail save

### ISSUE THREAD

**Issue by thystra** [foundryvtt/foundryvtt-premium-content#784]
### What happened?

Synaptic static should to offer to apply penalty to attack rolls, ability checks, and concentration saves (-1d6) on an failed intelligence save. Should also prompt for int save on end of turn/change of turn in combat while effect is active until ended by a successful save

### What package are you reporting this for?

Dungeons & Dragons Player's Handbook

### Version

1.2.0

**Comment by mattexdee** [comment]
Synaptic Static includes a `Muddled Thoughts` active effect which applies the 1d6 penalty automatically after you've applied it to any tokens who failed the save.

The game system does not currently support end of turn save requests but you can easily right click on the spell's chat card, pop it out, and continue to roll the saves easily from the popped out card. Since this isn't a bug I'll go ahead and close this issue.
